const KEY='ledgerhr-data-v1', AUTH='ledgerhr-auth-v1';
const blank={employees:[],attendance:[],leave:[],payroll:[],deadline:'2026-09-30'};let db=load();let current='dashboard';
const $=s=>document.querySelector(s);const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function load(){try{return {...blank,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...blank}}}function save(){localStorage.setItem(KEY,JSON.stringify(db));}
async function hash(v){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function money(v){return new Intl.NumberFormat('en-PG',{style:'currency',currency:'PGK',minimumFractionDigits:2}).format(Number(v)||0)}function date(v){return v?new Date(v+'T00:00:00').toLocaleDateString('en-GB'):''}function emp(id){return db.employees.find(x=>x.id===id)?.name||'Unknown employee'}function id(){return crypto.randomUUID()}
function notify(){const n=db.leave.filter(x=>x.status==='Pending').length;$('#nav-badge').textContent=n;$('#nav-badge').classList.toggle('hidden',!n)}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2500)}
function openModal(title,body){document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="modal"><div class="modal"><h3>${title}</h3>${body}</div></div>`);$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()})}function closeModal(){$('#modal')?.remove()}
function employeeOptions(){return db.employees.map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join('')}
function render(){notify();const titles={dashboard:'Dashboard',employees:'Employees',attendance:'Attendance',leave:'Leave',payroll:'Payroll',notifications:'Notifications'};$('#page-title').textContent=titles[current];document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===current));$('#content').innerHTML=views[current]();}
const views={dashboard:()=>{const total=db.payroll.reduce((a,x)=>a+Number(x.net||0),0),pending=db.leave.filter(x=>x.status==='Pending').length;return `<div class="stats"><div class="stat"><span class="icon">♙</span><h3>${db.employees.length}</h3><p>Total employees</p></div><div class="stat"><span class="icon">◷</span><h3>${db.attendance.length}</h3><p>Attendance logs</p></div><div class="stat"><span class="icon">▣</span><h3>${pending}</h3><p>Pending leave</p></div><div class="stat"><span class="icon">₱</span><h3>${money(total)}</h3><p>Payroll total</p></div></div><div class="grid-2"><section class="panel"><div class="panel-head"><h3>Recent attendance</h3><button class="secondary" onclick="go('attendance')">View all</button></div>${db.attendance.length?`<table><tbody>${db.attendance.slice(-5).reverse().map(x=>`<tr><td><strong>${esc(emp(x.employee))}</strong><br><small>${date(x.date)}</small></td><td>${x.timeIn||'—'} – ${x.timeOut||'—'}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No attendance logs yet.</div>'}</section><section class="panel"><div class="panel-head"><h3>Action reminders</h3><button class="secondary" onclick="go('notifications')">View all</button></div>${reminders()||'<div class="empty">You are all caught up.</div>'}</section></div>`},
employees:()=>`<div class="page-head"><div><p class="eyebrow">DIRECT RECORD MANAGEMENT</p><h3>Employees</h3></div><button class="primary" onclick="employeeForm()">+ Add employee</button></div><section class="panel table-wrap"><table><thead><tr><th>Name</th><th>Department</th><th>Role</th><th>Contact</th><th>Hire date</th><th></th></tr></thead><tbody>${db.employees.length?db.employees.map(e=>`<tr><td><strong>${esc(e.name)}</strong></td><td>${esc(e.department)}</td><td>${esc(e.role)}</td><td>${esc(e.contact)}</td><td>${date(e.hireDate)}</td><td class="inline-actions"><button onclick="employeeForm('${e.id}')">Edit</button><button onclick="removeItem('employees','${e.id}')">Delete</button></td></tr>`).join(''):'<tr><td colspan="6" class="empty">No employees. Add your first employee.</td></tr>'}</tbody></table></section>`,
attendance:()=>`<div class="page-head"><div><p class="eyebrow">MANUAL TIME LOGS</p><h3>Attendance</h3></div><button class="primary" onclick="attendanceForm()">+ Log attendance</button></div><section class="panel table-wrap"><table><thead><tr><th>Employee</th><th>Date</th><th>Time in</th><th>Time out</th><th></th></tr></thead><tbody>${db.attendance.length?db.attendance.slice().reverse().map(x=>`<tr><td>${esc(emp(x.employee))}</td><td>${date(x.date)}</td><td>${x.timeIn||'—'}</td><td>${x.timeOut||'—'}</td><td class="inline-actions"><button onclick="attendanceForm('${x.id}')">Edit</button><button onclick="removeItem('attendance','${x.id}')">Delete</button></td></tr>`).join(''):'<tr><td colspan="5" class="empty">No attendance logs yet.</td></tr>'}</tbody></table></section>`,
leave:()=>`<div class="page-head"><div><p class="eyebrow">REQUEST REVIEW</p><h3>Leave requests</h3></div><button class="primary" onclick="leaveForm()">+ Add request</button></div><section class="panel table-wrap"><table><thead><tr><th>Employee</th><th>Leave type</th><th>Dates</th><th>Status</th><th></th></tr></thead><tbody>${db.leave.length?db.leave.slice().reverse().map(x=>`<tr><td>${esc(emp(x.employee))}</td><td>${esc(x.type)}</td><td>${date(x.start)} – ${date(x.end)}</td><td><span class="pill ${x.status.toLowerCase()}">${x.status}</span></td><td class="inline-actions">${x.status==='Pending'?`<button onclick="setLeave('${x.id}','Approved')">Approve</button><button onclick="setLeave('${x.id}','Denied')">Deny</button>`:''}<button onclick="removeItem('leave','${x.id}')">Delete</button></td></tr>`).join(''):'<tr><td colspan="5" class="empty">No leave requests yet.</td></tr>'}</tbody></table></section>`,
payroll:()=>{const total=db.payroll.reduce((a,x)=>a+Number(x.net||0),0);return `<div class="page-head"><div><p class="eyebrow">PGK PAYROLL</p><h3>Payroll <small class="muted">${money(total)} total net pay</small></h3></div><div class="toolbar"><button class="secondary" onclick="exportPayroll()">Export CSV</button><button class="secondary" onclick="exportBSP()">BSP bank file</button><button class="primary" onclick="payrollForm()">+ Add payroll</button></div></div><section class="panel table-wrap"><table><thead><tr><th>Employee</th><th>Month</th><th>Salary</th><th>Deductions</th><th>Net pay</th><th></th></tr></thead><tbody>${db.payroll.length?db.payroll.slice().reverse().map(x=>`<tr><td>${esc(emp(x.employee))}</td><td>${date(x.month)}</td><td class="money">${money(x.salary)}</td><td class="money">${money(x.deductions)}</td><td class="money positive">${money(x.net)}</td><td class="inline-actions"><button onclick="payslip('${x.id}')">Payslip</button><button onclick="payrollForm('${x.id}')">Edit</button><button onclick="removeItem('payroll','${x.id}')">Delete</button></td></tr>`).join(''):'<tr><td colspan="6" class="empty">No payroll records yet.</td></tr>'}</tbody></table></section>`},
notifications:()=>`<div class="page-head"><div><p class="eyebrow">ONLY ACTIONABLE REMINDERS</p><h3>Notifications</h3></div></div><section class="panel">${reminders()||'<div class="empty">No payroll deadlines or pending leave requests.</div>'}</section>`};
function reminders(){let a=db.leave.filter(x=>x.status==='Pending').map(x=>`<div class="notice">▣ <div><strong>Pending leave request</strong><small>${esc(emp(x.employee))} · ${esc(x.type)} · ${date(x.start)}</small></div></div>`);if(db.deadline)a.unshift(`<div class="notice">₱ <div><strong>Payroll deadline</strong><small>Next payroll deadline: ${date(db.deadline)}</small></div></div>`);return a.join('')}
function formField(label,name,type='text',value=''){return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" required></label>`}
function employeeForm(edit){const e=db.employees.find(x=>x.id===edit)||{};openModal(edit?'Edit employee':'Add employee',`<form id="record-form"><div class="form-grid">${formField('Name','name','text',e.name)}${formField('Department','department','text',e.department)}${formField('Role','role','text',e.role)}${formField('Contact','contact','text',e.contact)}${formField('Hire date','hireDate','date',e.hireDate)}</div><div class="modal-actions"><button type="button" class="secondary" onclick="closeModal()">Cancel</button><button class="primary">Save employee</button></div></form>`);$('#record-form').onsubmit=ev=>{ev.preventDefault();const o=Object.fromEntries(new FormData(ev.target));if(edit)Object.assign(e,o);else db.employees.push({id:id(),...o});save();closeModal();render();toast('Employee saved')};}
function attendanceForm(edit){const a=db.attendance.find(x=>x.id===edit)||{};openModal(edit?'Edit attendance':'Log attendance',`<form id="record-form"><div class="form-grid"><label>Employee<select name="employee" required>${employeeOptions()}</select></label>${formField('Date','date','date',a.date)}${formField('Time in','time','time',a.timeIn)}${formField('Time out','time','time',a.timeOut)}</div><div class="modal-actions"><button type="button" class="secondary" onclick="closeModal()">Cancel</button><button class="primary">Save log</button></div></form>`);if(a.employee)$('#record-form [name=employee]').value=a.employee;$('#record-form').onsubmit=ev=>{ev.preventDefault();const o=Object.fromEntries(new FormData(ev.target));if(edit)Object.assign(a,o);else db.attendance.push({id:id(),...o});save();closeModal();render();toast('Attendance saved')};}
function leaveForm(edit){const a=db.leave.find(x=>x.id===edit)||{status:'Pending'};openModal('Leave request',`<form id="record-form"><div class="form-grid"><label>Employee<select name="employee" required>${employeeOptions()}</select></label>${formField('Leave type','type','text',a.type)}${formField('Start date','start','date',a.start)}${formField('End date','end','date',a.end)}<label>Status<select name="status"><option>Pending</option><option>Approved</option><option>Denied</option></select></label></div><div class="modal-actions"><button type="button" class="secondary" onclick="closeModal()">Cancel</button><button class="primary">Save request</button></div></form>`);$('#record-form [name=employee]').value=a.employee||'';$('#record-form [name=status]').value=a.status;$('#record-form').onsubmit=ev=>{ev.preventDefault();const o=Object.fromEntries(new FormData(ev.target));if(edit)Object.assign(a,o);else db.leave.push({id:id(),...o});save();closeModal();render();toast('Leave request saved')};}
function payrollForm(edit){const a=db.payroll.find(x=>x.id===edit)||{};openModal(edit?'Edit payroll':'Add payroll',`<form id="record-form"><div class="form-grid"><label>Employee<select name="employee" required>${employeeOptions()}</select></label>${formField('Month','month','date',a.month)}${formField('Salary (PGK)','salary','number',a.salary)}${formField('Deductions (PGK)','deductions','number',a.deductions)}</div><p class="muted">Net Pay is automatically calculated as Salary − Deductions.</p><div class="modal-actions"><button type="button" class="secondary" onclick="closeModal()">Cancel</button><button class="primary">Save payroll</button></div></form>`);$('#record-form [name=employee]').value=a.employee||'';$('#record-form').onsubmit=ev=>{ev.preventDefault();const o=Object.fromEntries(new FormData(ev.target));o.net=Math.max(0,Number(o.salary||0)-Number(o.deductions||0));if(edit)Object.assign(a,o);else db.payroll.push({id:id(),...o});save();closeModal();render();toast('Payroll saved')};}
function setLeave(i,status){const x=db.leave.find(x=>x.id===i);x.status=status;save();render();toast(`Leave ${status.toLowerCase()}`)}function removeItem(type,i){if(confirm('Delete this record?')){db[type]=db[type].filter(x=>x.id!==i);save();render();}}
function csv(rows){return rows.map(r=>r.map(x=>`"${String(x??'').replaceAll('"','""')}"`).join(',')).join('\n')}function download(name,text,type='text/csv'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click()}
function exportPayroll(){download('payroll-pgk.csv',csv([['Employee','Month','Salary PGK','Deductions PGK','Net Pay PGK'],...db.payroll.map(x=>[emp(x.employee),x.month,x.salary,x.deductions,x.net])]));toast('Payroll CSV exported')}
function exportBSP(){download('bsp-bank-file-pgk.csv',csv([['Account Name','Employee ID','Currency','Amount','Reference'],...db.payroll.map(x=>[emp(x.employee),x.employee,'PGK',x.net,`SALARY-${x.month}`])]));toast('BSP bank file exported')}
function payslip(i){const x=db.payroll.find(x=>x.id===i);const w=window.open('','_blank');w.document.write(`<html><head><title>PGK Payslip</title><style>body{font:16px Arial;padding:50px;color:#17253d}h1{color:#3977c9}table{border-collapse:collapse;width:500px}td{padding:12px;border-bottom:1px solid #ddd}td:last-child{text-align:right}@media print{button{display:none}}</style></head><body><h1>LedgerHR</h1><h2>PAYSLIP</h2><p><b>Employee:</b> ${esc(emp(x.employee))}<br><b>Pay month:</b> ${date(x.month)}<br><b>Currency:</b> PGK</p><table><tr><td>Salary</td><td>${money(x.salary)}</td></tr><tr><td>Deductions</td><td>${money(x.deductions)}</td></tr><tr><td><b>Net Pay</b></td><td><b>${money(x.net)}</b></td></tr></table><br><button onclick="print()">Print / Save as PDF</button></body></html>`);w.document.close()}
function go(v){current=v;render()}document.querySelectorAll('.nav-item').forEach(x=>x.onclick=()=>go(x.dataset.view));
$('#backup-btn').onclick=()=>download('ledgerhr-backup.json',JSON.stringify(db,null,2),'application/json');$('#restore-file').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{db={...blank,...JSON.parse(r.result)};save();render();toast('Backup restored')}catch{toast('Invalid backup file')}};r.readAsText(f)};$('#logout').onclick=()=>{sessionStorage.removeItem('ledgerhr-session');location.reload()};
async function init(){if(!localStorage.getItem(AUTH))$('#setup-note').classList.remove('hidden');$('#login-form').onsubmit=async e=>{e.preventDefault();const p=$('#password').value;if(p.length<8){$('#login-error').textContent='Use at least 8 characters.';return}const h=await hash(p),existing=localStorage.getItem(AUTH);if(!existing)localStorage.setItem(AUTH,h);if(h!==localStorage.getItem(AUTH)){$('#login-error').textContent='Incorrect Accountant password.';return}sessionStorage.setItem('ledgerhr-session','yes');$('#auth').classList.add('hidden');$('#app').classList.remove('hidden');render()};if(sessionStorage.getItem('ledgerhr-session')){$('#auth').classList.add('hidden');$('#app').classList.remove('hidden');render()}}init();
